[package]
name = "lambstock"
version = "0.1.0"
authors = ["softprops <d.tangren@gmail.com>"]

[dependencies]
failure = "0.1"
futures = "0.1"
humansize  = "1.1"
lazy_static = "1.1"
rusoto_resourcegroupstaggingapi = "0.33"
rusoto_lambda = "0.33"
structopt = "0.2"
tokio = "0.1"